/*INSERTA SECCIONES*/
INSERT INTO gameshub.sections (`id`,`name`,`create_time`,`update_time`) VALUES (1,'Ofertas','2022-12-18 09:54:59',NULL);
INSERT INTO gameshub.sections (`id`,`name`,`create_time`,`update_time`) VALUES (2,'Recomendados','2022-12-18 09:54:59',NULL);
INSERT INTO gameshub.sections (`id`,`name`,`create_time`,`update_time`) VALUES (3,'Mas vendidos','2022-12-18 09:54:59',NULL);

/*INSERTA CATEGORIAS*/
INSERT INTO gameshub.categories (`id`,`name`,`create_time`,`update_time`) VALUES (1,'Accion','2022-12-18 09:49:06',NULL);
INSERT INTO gameshub.categories (`id`,`name`,`create_time`,`update_time`) VALUES (2,'Deportes','2022-12-18 09:49:06',NULL);
INSERT INTO gameshub.categories (`id`,`name`,`create_time`,`update_time`) VALUES (3,'Estrategia','2022-12-18 09:49:06',NULL);
INSERT INTO gameshub.categories (`id`,`name`,`create_time`,`update_time`) VALUES (4,'Arcade','2022-12-18 09:50:37',NULL);
INSERT INTO gameshub.categories (`id`,`name`,`create_time`,`update_time`) VALUES (5,'Aventura','2022-12-18 09:50:37',NULL);

/*INSERTA CONSOLAS*/
INSERT INTO gameshub.consoles (`id`,`name`,`create_time`,`update_time`) VALUES (1,'Pc','2022-12-18 09:52:06',NULL);
INSERT INTO gameshub.consoles (`id`,`name`,`create_time`,`update_time`) VALUES (2,'Xbox 360','2022-12-18 09:52:06',NULL);
INSERT INTO gameshub.consoles (`id`,`name`,`create_time`,`update_time`) VALUES (3,'Xbox One','2022-12-18 09:52:06',NULL);
INSERT INTO gameshub.consoles (`id`,`name`,`create_time`,`update_time`) VALUES (4,'Ps4','2022-12-18 09:52:06',NULL);
INSERT INTO gameshub.consoles (`id`,`name`,`create_time`,`update_time`) VALUES (5,'Ps5','2022-12-18 09:52:06',NULL);
INSERT INTO gameshub.consoles (`id`,`name`,`create_time`,`update_time`) VALUES (6,'Nintendo switch','2022-12-18 09:52:06',NULL);
INSERT INTO gameshub.consoles (`id`,`name`,`create_time`,`update_time`) VALUES (7,'Nintendo Wii','2022-12-18 09:52:06',NULL);

/*INSERTA PRODUCTOS*/
/*
INSERT INTO gameshub.games (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`categories_id`,`sections_id`,`create_time`,`update_time`) VALUES (1,'Mortal Kombat XL','Mortal Kombat XL es una edición mejorada y revisada de Mortal Kombat X, que incluirá el juego principal y los contenidos del Kombat Pack 1 y 2, además de futuros paquetes como Apocalypse, y los skins de los packs de trajes y apariencias lanzados con anterioridad.','ggdfgdg',12,12.5,10.35,1,2,'2022-12-18 09:57:18',NULL);
INSERT INTO gameshub.games (`id`,`name`, `description`, `image`, `value`, `discount`, `final_value`, `categories_id`, `sections_id`, `create_time`) VALUES (2,'Quake 4', '\"Quake 4 es la nueva entrega de Quake, la popular saga de videojuegos de acción en primera persona creada por John Romero, John Carmack y American McGee. Apostando por un diseño enfocado en los eSports y la vertiente online y competitiva, Quake Champions es una reformulación de Quake con nuevos ingredientes, mejores gráficos y la misma jugabilidad sólida y frenética de siempre.', 'gygytrguyfgy', '12', '15', '10', '2', '3', '2022-12-18 09:57:18');
*/
/*
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (1,"Mortal Kombat XL","Mortal Kombat XL es una edición mejorada y revisada de Mortal Kombat X, que incluirá el juego principal y los contenidos del Kombat Pack 1 y 2, además de futuros paquetes como Apocalypse, y los skins de los packs de trajes y apariencias lanzados con anterioridad.","/images/main-cards/mkxl.jpeg",9.99,25,7.49,1,2,"2022-12-18 09:57:18",NULL,null);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (2,"Quake 4","Quake 4 es la nueva entrega de Quake, la popular saga de videojuegos de acción en primera persona creada por John Romero, John Carmack y American McGee. Apostando por un diseño enfocado en los eSports y la vertiente online y competitiva, Quake Champions es una reformulación de Quake con nuevos ingredientes, mejores gráficos y la misma jugabilidad sólida y frenética de siempre.","/images/main-cards/quake.jpeg",7.65,20.5,6.08,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (3,"Human Fall Flat","Human: Fall Flat se trata de un juego de puzles en tercera persona basado en el uso de la física y en el que el desarrollo no lineal será esencial para desarrollar su aspecto de elecciones esenciales para el jugador. El título nos pone en el papel de Bob, quien debe moverse por una serie de escenarios oníricos buscando una salida, mientras que, para complicar más la jugabilidad, el jugador tendrá que controlar cada extremidad de forma independiente.","/images/main-cards/humanfallflat.jpg",9.99,15,8.49,2,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (4,"Terraria","El considerado 'hermano en 2D de Minecraft', nos lleva a un mundo único en el que tenemos que sobrevivir utilizando ingeniosamente las herramientas que se ponen a nuestra disposición. Así, comenzamos con una espada corta de cobre, un pico y un hacha. La primera nos valdrá para derrotar algunos enemigos, los inofensivos slime verdes, el pico para cavar y conseguir materiales como bloques de tierra, piedras y otros minerales, y el hacha para talar árboles y conseguir madera.","/images/main-cards/terraria.jpg",11.99,15,10.19,2,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (5,"Cyberpunk 2077","Cyberpunk 2077 es el nuevo videojuego de rol en primera persona con estructura de mundo abierto de CD Projekt RED. Los padres de The Witcher nos presentan para Xbox One, PC y PS4 una aventura de corte futurista y ciberpunk en la que encarnaremos a un personaje diseñado a nuestra medida y en la que tendremos que sobrevivir en una peligrosa urbe plagada de corporaciones, ciborgs, bandas y las más variadas amenazas tecnológicas.","/images/main-cards/cyberpunk.jpeg",6.99,15,5.94,3,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (6,"Fortnite - Season 4","Fortnite Battle Royale es la variante ‘battle royale’ gratuita multijugador de Fortnite, el videojuego de Epic Games. Cogiendo las bases jugables del título de acción, construcción y supervivencia, los padres de Paragon han diseñado una propuesta similar a la del todopoderoso PUBG pero con sus propias ideas, tanto en consolas como PlayStation 4 y Xbox One, como en PC.","/images/main-cards/fortnite.jpeg",3.99,15,3.39,1,2,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (7,"PlayStation Card","Disfruta de accesos anticipados y suscripciones a juegos para estar al día con las últimas noticias y mantenerte conectado con toda la comunidad de PlayStation!","/images/main-cards/playstation-store.jpeg",9.99,15,8.49,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (8,"ARK Survival Evolved","ARK: Survival Evolved para PC es un nuevo juego de supervivencia y mundo abierto. A lo largo de la aventura tendremos que cazar para sobrevivir, crear objetos, mejorar nuestra tecnología, construir refugios, etcétera. Todo ello mientras exploramos una gigantesca isla repleta de dinosaurios, lo que se perfila como uno de sus mayores atractivos.","/images/main-cards/ark-survival.jpeg",9.99,15,8.49,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (9,"Counter Strike","La cuarta versión de Counter-Strike llega a PC 12 años después que el juego original manteniendo la fórmula que lo convirtió en un fenómeno, pero también añadiendo nuevo contenido. Usa un nuevo motor gráfico que permite un salto visual, renovando mapas clásicos como de_dust, y añade nuevos mapas, facciones y modos de juego, volviendo a intentar enganchar a millones de jugadores en partidas por equipos entre terroristas y fuerzas del orden.","/images/main-cards/cs-anthology.jpg",3.99,15,3.39,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (10,"Doom Eternal - Deluxe","DOOM Eternal es la secuela del éxito de 2016, DOOM. Ahondando de nuevo en las raíces clásicas del género de acción en primera persona, la segunda parte desarrollada por id Software y Bethesda sigue apostando por la guerra sin cuartel contra los demonios en Xbox One, PS4, PC y Nintendo Switch.","/images/main-cards/doom-eternal.jpeg",3.99,15,3.39,1,3,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (11,"COD - Infinite Warfare","Call of Duty: Infinite Warfare es un juego de acción bélica futurista que presentará guerras a gran escala con su habitual narrativa militar. Se nos ofrecerá una nueva historia donde los jugadores deberán luchar contra el Settlement Defense Front para defender nuestro modo de vida a través del Sistema Solar. Esta nueva entrega de acción en primera persona, añadirá armas futuristas, pilotaje de naves espaciales y vehículos y una nueva serie de modos de juego, que volverán a ofrecernos características online y raciones de zombis.","/images/main-cards/cod-infinite.jpg",3.99,15,3.39,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (12,"Captain Tsubasa","Captain Tsubasa: Rise of the New Champions es un videojuego de fútbol arcade con toques de rol de acción desarrollado para PlayStation 4, Nintendo Switch y PC por Bandai Namco y Tamsoft. Adaptando la saga de anime y manga Captain Tsubasa, también conocida como Oliver y Benji, busca ofrecer partidos espectaculares con todo el carisma de la serie de animación, permitiéndonos disfrutar de personajes Tsubasa Ōzora, Kojirō Hyūga, Genzo Wakabayashi o Tarō Misaki.","/images/main-cards/captain-tsubasa.jpeg",5.99,15,5.09,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (13,"Dragon Ball Z Kakarot","Dragon Ball Game Project Z: Action RPG es un nuevo videojuego de rol y acción basado en Dragon Ball para Xbox One, PC y PS4 que nos narrará las aventuras de Goku durante la saga de Dragon Ball Z. Según ha confirmado CyberConnect2, responsables del videojuego, el título se centra en una de las etapas doradas del manga y el anime, contándonos los eventos sucedidos en aquellos momentos de una forma inédita y muy espectacular.","/images/main-cards/dbz-kakarot.jpeg",3.99,15,3.39,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (14,"FIFA 23","EA SPORTS™ FIFA 23 lleva El Juego de Todos al campo con los torneos de la Copa Mundial de la FIFA™ masculina y femenina, la incorporación de clubes femeninos y nuevas formas de jugar tus modos favoritos. Los avances en la tecnología HyperMotion2 proporcionan aún más acción y realismo al campo de juego en PS5.","/images/main-cards/fifa23.jpg",19.99,15,16.99,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (15,"Monster Hunter World","Monster Hunter World es el retorno de la serie a las consolas de sobremesa, permitiéndonos cazar criaturas gigantes en un entorno salvaje, ya sea en solitario o con tres cazadores con un nuevo sistema multijugador drop-in que permite cooperativo entre regiones. Mantendrá las señas de identidad, su sistema de creación y equipamiento para cazar monstruos, mientras mejoramos nuestras habilidades. Los recursos se podrán utilizar para mejoras y otro equipamiento. Su jugabilidad facilita explorar el mapa sin transiciones, con ciclo horario.","/images/main-cards/mhw.jpeg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (16,"Crash Bandicoot Trilogy","Se trata de una remasterización de los tres primeros juegos de la serie Crash Bandicoot aparecidos en la consola PlayStation a finales de los 90 y desarrollados por Naughty Dog, pero mejorados con gráficos totalmente renovados, cambios estéticos y ciertas novedades jugables.","/images/main-cards/crashbandicoot.jpeg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (17,"Days Gone","Days Gone es el videojuego de acción, zombies y supervivencia en mundo abierto exclusivo para PlayStation 4 desarrollado por Bend Studio. Nos invitará, encarnando al motero Deacon St. John, a sobrevivir en un escenario rural y desolado ambientado en la época actual plagado de voraces seres infectados por un misterioso virus.","/images/main-cards/daysgone.jpeg",6.99,30,4.89,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (18,"Devil May Cry 5","Devil May Cry 5 es la quinta entrega de la serie de juegos de acción en tercera persona o ‘hack and slash’ de Capcom para Xbox One, PS4 y PC, además de PS5 y Xbox Series X/S. Retomando la saga después del lanzamiento de la cuarta parte, hace diez años, Hideaki Itsuno director del título y de la mayoría de los capítulos de las aventuras de Dante, promete una vuelta a los orígenes y una jugabilidad frenética y desafiante con distintos personajes.","/images/main-cards/devilmaycry5.jpeg",6.99,20,5.59,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (19,"Devil May Cry HD","Comercializada en Xbox 360 y PlayStation 3 en 2012, Devil May Cry HD Collection es la versión diseñada para la actual generación de consolas y plataformas. Devil May Cry HD Collection llegará a Xbox One, PS4 y PC, e incluirá Devil May Cry, Devil May Cry 2 y Devil May Cry 3: Dante’s Awakening – Special Edition, así como gráficos en alta definición y 60 frames por segundo.","/images/main-cards/devilmaycryHD.jpeg",6.99,4,6.71,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (20,"Duke Nukem Forever","El antihéroe Duke Nukem regresa a Xbox 360 en su aventura más esperada, que ha estado la friolera de 14 años en desarrollo y a punto de ser cancelada varias veces. Duke Nukem Forever resucita a Duke con todo lo que eso conlleva: policías-cerdo volando por los aires, comentarios machistas y subidos de tono, y batallas contra jefes finales gigantes usando un largo repertorio de armas. Apuesta por una jugabilidad clásica, como la de los juegos de acción en primera persona de los años noventa, e incluye un modo multijugador online.","/images/main-cards/dukenuken.jpg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (21,"God of War","God of War: Ragnarok para PlayStation 5 es la secuela de God of War, el reinicio y a la vez secuela de los anteriores God of War para consolas PlayStation. Desarrollado por el prestigioso estudio Sony Santa Monica y con la dirección de Cory Barlog, encontraremos una nueva historia en la que Kratos deberá enfrentarse a diversos enemigos de inspiración nórdica. Explorando los mitos del Ragnarok, el apocalipsis que todo lo devorará según esta tradición del norte, la secuela se espera que llegue en 2021.","/images/main-cards/godofwar.jpeg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (22,"Mafia III","En la tercera entrega de la reputada saga Mafia, nos moveremos por New Bourdeaux, una ciudad inspirada en Nueva Orleans, en el año 1968, moviéndonos por los bajos fondos, entablando contactos con la mafia y entrando en la guerra de intereses y bandas de la época. El título de mundo abierto de 2K Games y Hangar 13, apostará por incluir nuevas mecánicas de negocios, un mayor plantel de vehículos y armas y una narrativa que hará homenaje a las clásicas películas del género negro.","/images/main-cards/mafiaIII.jpeg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (23,"GTA V","Grand Theft Auto V para PS5 es una versión mejorada y ampliada del GTA V original aparecido en PS3 en 2013. Contará con mejoras gráficas y el nuevo contenido incluido en su versión de PS4, como armas, vehículos o misiones, además de una banda sonora ampliada y GTA Online. Nos cuenta la épica historia de Michael, Franklin y Trevor en la ciudad de Los Santos y sus alrededores.","/images/main-cards/gtaV.jpeg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (24,"Hollow Knight","Hollow Knight, desarrollado por Team Cherry, ofrecerá una aventura de estilo bidimensional que combinará acción y plataformas en un mundo de fantasía medieval, el reino de Hallownest. Incluirá animaciones hechas con estilo tradicional, retos para el jugador, coleccionables por desbloquear y una banda sonora única.","/images/main-cards/hollowknight.jpeg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (25,"Visage","Visage es un videojuego de terror en primera persona desarrollado por SadSquare Studio, con énfasis en el horror psicológico, que nos llevará a vivir una serie de sucesos paranormales ambientados en los años ochenta, en un pueblo apartado y en un caserón enorme. Está pensado para consolas y PC.","/images/main-cards/visage.jpeg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (26,"Evil West","Una oscura amenaza consume la frontera americana. Como uno de los últimos agentes de una institución ultrasecreta dedicada a cazar vampiros, eres la última línea de defensa de la humanidad contra un terror profundamente arraigado que emerge ahora de entre las sombras. Álzate y conviértete en un superhéroe del salvaje Oeste, erradica la amenaza de los vampiros y ¡salva a los Estados Unidos!","/images/main-cards/evilwest.jpeg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (27,"Just Dance 2023","Just Dance 2023 Edition es el décimo cuarto videojuego de ritmo de baile de la serie Just Dance, precedido por Just Dance 2022, desarrollado y publicado por Ubisoft. Esta programado a lanzar el 22 de noviembre de 2022 para Nintendo Switch, PlayStation 5 y Xbox Series X y Series S, y en una fecha posterior para PC.","/images/main-cards/justdance2023.jpg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (28,"LOTR Gollum","The Lord of the Rings: Gollum, desarrollado y editado por Daedalic Entertainment para PC, PlayStation 4, Xbox One, Switch, PlayStation 5 y Xbox Series, es una aventura de acción centrada en la historia. Embárcate en un peligroso viaje como Gollum, en busca del único tesoro que conoce. Gollum es hábil y astuto, pero su personalidad está dividida. Una mente, dos egos: ¡tú decides!","/images/main-cards/lotrgollum.jpeg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (29,"Midnight Suns","Marvel's Midnight Suns es un nuevo RPG táctico ambientado en el lado más oscuro del Universo Marvel. Forma un equipo con los Midnight Suns y vive entre ellos mientras luchas contra las fuerzas demoníacas del inframundo para evitar que Lilith, la Madre de los Demonios, resucite a su maestro Chthon.","/images/main-cards/marvelmidnightsuns.jpeg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (30,"Naruto Storm Trilogy","Naruto: Ultimate Ninja Storm Trilogy es un recopilatorio exclusivo de la distribución digital que incluye los tres primeros juegos numerados de esta exitosa saga de juegos de lucha basados en el famoso manga creado por Masashi Kishimoto.","/images/main-cards/narutostorm.jpeg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (31,"One Piece Oddysey","One Piece Odyssey es un videojuego de rol y combates por turnos ambientado en el universo del exitoso manganime, si bien cuenta con una historia original y nuevos personajes que fueron creados bajo la atenta supervisión del mismísimo creador de la serie, Eiichiro Oda.","/images/main-cards/onepieceodyssey.jpeg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (32,"Park Beyond","¡En Park Beyond podrás crear el parque de tus sueños sin preocuparte por la fuerza de la gravedad! Una empresa en horas bajas te ha contratado para que, gracias a tu visionaria concepción de la arquitectura, construyas los parques temáticos más descabellados. Podrás crear esas atracciones con las que siempre habías soñado pero que no pueden existir en el mundo real. Forma equipo con Phil, un entusiasta veterano en esto de los parques; Izzy, una ejecutiva estricta pero afable, y un montón de alegres y apasionados personajes para construir una exitosa y rentable empresa de parques de atracciones.","/images/main-cards/parkbeyond.jpeg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (33,"Residen Evil 4","Resident Evil 4 es un remake del Resident Evil 4 original del 2005. Survival Horror de última generación reimaginado para el año 2023. Resident Evil 4 conserva la esencia del juego original, a la vez que introduce mecánicas de juego actualizadas, una historia reimaginada, e impresionantes gráficos de última generación que lo convierten en la experiencia de Survival Horror definitiva en la cual se cruzan la vida y la muerte, el terror y la catarsis.","/images/main-cards/re4.jpg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (34,"SpiderMan Miles Morales","¡Cava, lucha y construye! El mundo mismo está al alcance de tu mano mientras luchas por la supervivencia, la fortuna y la gloria. Adéntrate en extensiones cavernosas, busca enemigos cada vez más grandes para poner a prueba tu temple en combate o construye tu propia ciudad. ¡En el mundo de Terraria, la elección es tuya! Combinando elementos de los juegos de acción clásicos con la libertad de la creatividad estilo sandbox, Terraria es una experiencia de juego única en la que tanto el viaje como el destino son tan únicos como los propios jugadores.","/images/main-cards/spiderman.jpg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (35,"Steam Gift Card","¡Cava, lucha y construye! El mundo mismo está al alcance de tu mano mientras luchas por la supervivencia, la fortuna y la gloria. Adéntrate en extensiones cavernosas, busca enemigos cada vez más grandes para poner a prueba tu temple en combate o construye tu propia ciudad. ¡En el mundo de Terraria, la elección es tuya! Combinando elementos de los juegos de acción clásicos con la libertad de la creatividad estilo sandbox, Terraria es una experiencia de juego única en la que tanto el viaje como el destino son tan únicos como los propios jugadores.","/images/main-cards/steamcard.jpeg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (36,"The Devil In Me","¡Cava, lucha y construye! El mundo mismo está al alcance de tu mano mientras luchas por la supervivencia, la fortuna y la gloria. Adéntrate en extensiones cavernosas, busca enemigos cada vez más grandes para poner a prueba tu temple en combate o construye tu propia ciudad. ¡En el mundo de Terraria, la elección es tuya! Combinando elementos de los juegos de acción clásicos con la libertad de la creatividad estilo sandbox, Terraria es una experiencia de juego única en la que tanto el viaje como el destino son tan únicos como los propios jugadores.","/images/main-cards/thedevilinme.jpg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (37,"Thief","¡Cava, lucha y construye! El mundo mismo está al alcance de tu mano mientras luchas por la supervivencia, la fortuna y la gloria. Adéntrate en extensiones cavernosas, busca enemigos cada vez más grandes para poner a prueba tu temple en combate o construye tu propia ciudad. ¡En el mundo de Terraria, la elección es tuya! Combinando elementos de los juegos de acción clásicos con la libertad de la creatividad estilo sandbox, Terraria es una experiencia de juego única en la que tanto el viaje como el destino son tan únicos como los propios jugadores.","/images/main-cards/thief.jpeg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (38,"Xbox Card $10","¡Cava, lucha y construye! El mundo mismo está al alcance de tu mano mientras luchas por la supervivencia, la fortuna y la gloria. Adéntrate en extensiones cavernosas, busca enemigos cada vez más grandes para poner a prueba tu temple en combate o construye tu propia ciudad. ¡En el mundo de Terraria, la elección es tuya! Combinando elementos de los juegos de acción clásicos con la libertad de la creatividad estilo sandbox, Terraria es una experiencia de juego única en la que tanto el viaje como el destino son tan únicos como los propios jugadores.","/images/main-cards/xbox10.jpeg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (39,"Xbox Card $15","¡Cava, lucha y construye! El mundo mismo está al alcance de tu mano mientras luchas por la supervivencia, la fortuna y la gloria. Adéntrate en extensiones cavernosas, busca enemigos cada vez más grandes para poner a prueba tu temple en combate o construye tu propia ciudad. ¡En el mundo de Terraria, la elección es tuya! Combinando elementos de los juegos de acción clásicos con la libertad de la creatividad estilo sandbox, Terraria es una experiencia de juego única en la que tanto el viaje como el destino son tan únicos como los propios jugadores.","/images/main-cards/xbox15.jpeg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (40,"Xbox Card $50","¡Cava, lucha y construye! El mundo mismo está al alcance de tu mano mientras luchas por la supervivencia, la fortuna y la gloria. Adéntrate en extensiones cavernosas, busca enemigos cada vez más grandes para poner a prueba tu temple en combate o construye tu propia ciudad. ¡En el mundo de Terraria, la elección es tuya! Combinando elementos de los juegos de acción clásicos con la libertad de la creatividad estilo sandbox, Terraria es una experiencia de juego única en la que tanto el viaje como el destino son tan únicos como los propios jugadores.","/images/main-cards/xbox50.jpeg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (41,"Sonic Frontiers","¡Cava, lucha y construye! El mundo mismo está al alcance de tu mano mientras luchas por la supervivencia, la fortuna y la gloria. Adéntrate en extensiones cavernosas, busca enemigos cada vez más grandes para poner a prueba tu temple en combate o construye tu propia ciudad. ¡En el mundo de Terraria, la elección es tuya! Combinando elementos de los juegos de acción clásicos con la libertad de la creatividad estilo sandbox, Terraria es una experiencia de juego única en la que tanto el viaje como el destino son tan únicos como los propios jugadores.","/images/main-cards/sonic.jpeg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (42,"A Plague Tale","¡Cava, lucha y construye! El mundo mismo está al alcance de tu mano mientras luchas por la supervivencia, la fortuna y la gloria. Adéntrate en extensiones cavernosas, busca enemigos cada vez más grandes para poner a prueba tu temple en combate o construye tu propia ciudad. ¡En el mundo de Terraria, la elección es tuya! Combinando elementos de los juegos de acción clásicos con la libertad de la creatividad estilo sandbox, Terraria es una experiencia de juego única en la que tanto el viaje como el destino son tan únicos como los propios jugadores.","/images/main-cards/aplaguetale.jpg",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
INSERT INTO gameshub.products (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (43,"Juego de GamesHub","El mejor juego de la historia...realizado por gamesHub","/images/games/1669000750169.png",6.99,15,5.94,1,1,"2022-12-18 09:57:18",NULL,NULL);
*/


INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (1,'Mortal Kombat XL','Mortal Kombat XL es una edición mejorada y revisada de Mortal Kombat X, que incluirá el juego principal y los contenidos del Kombat Pack 1 y 2, además de futuros paquetes como Apocalypse, y los skins de los packs de trajes y apariencias lanzados con anterioridad.','/images/main-cards/mkxl.jpeg',9.99,25,7.49,1,2,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (2,'Quake 4','Quake 4 es la nueva entrega de Quake, la popular saga de videojuegos de acción en primera persona creada por John Romero, John Carmack y American McGee. Apostando por un diseño enfocado en los eSports y la vertiente online y competitiva, Quake Champions es una reformulación de Quake con nuevos ingredientes, mejores gráficos y la misma jugabilidad sólida y frenética de siempre.','/images/main-cards/quake.jpeg',7.65,20.5,6.08,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (3,'Human Fall Flat','Human: Fall Flat se trata de un juego de puzles en tercera persona basado en el uso de la física y en el que el desarrollo no lineal será esencial para desarrollar su aspecto de elecciones esenciales para el jugador. El título nos pone en el papel de Bob, quien debe moverse por una serie de escenarios oníricos buscando una salida, mientras que, para complicar más la jugabilidad, el jugador tendrá que controlar cada extremidad de forma independiente.','/images/main-cards/humanfallflat.jpg',9.99,15,8.49,2,2,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (4,'Terraria','El considerado \'hermano en 2D de Minecraft\', nos lleva a un mundo único en el que tenemos que sobrevivir utilizando ingeniosamente las herramientas que se ponen a nuestra disposición. Así, comenzamos con una espada corta de cobre, un pico y un hacha. La primera nos valdrá para derrotar algunos enemigos, los inofensivos slime verdes, el pico para cavar y conseguir materiales como bloques de tierra, piedras y otros minerales, y el hacha para talar árboles y conseguir madera.','/images/main-cards/terraria.jpg',11.99,15,10.19,2,3,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (5,'Cyberpunk 2077','Cyberpunk 2077 es el nuevo videojuego de rol en primera persona con estructura de mundo abierto de CD Projekt RED. Los padres de The Witcher nos presentan para Xbox One, PC y PS4 una aventura de corte futurista y ciberpunk en la que encarnaremos a un personaje diseñado a nuestra medida y en la que tendremos que sobrevivir en una peligrosa urbe plagada de corporaciones, ciborgs, bandas y las más variadas amenazas tecnológicas.','/images/main-cards/cyberpunk.jpeg',6.99,15,5.94,3,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (6,'Fortnite - Season 4','Fortnite Battle Royale es la variante ‘battle royale’ gratuita multijugador de Fortnite, el videojuego de Epic Games. Cogiendo las bases jugables del título de acción, construcción y supervivencia, los padres de Paragon han diseñado una propuesta similar a la del todopoderoso PUBG pero con sus propias ideas, tanto en consolas como PlayStation 4 y Xbox One, como en PC.','/images/main-cards/fortnite.jpeg',3.99,15,3.39,1,2,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (7,'PlayStation Card','Disfruta de accesos anticipados y suscripciones a juegos para estar al día con las últimas noticias y mantenerte conectado con toda la comunidad de PlayStation!','/images/main-cards/playstation-store.jpeg',9.99,15,8.49,2,3,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (8,'ARK Survival Evolved','ARK: Survival Evolved para PC es un nuevo juego de supervivencia y mundo abierto. A lo largo de la aventura tendremos que cazar para sobrevivir, crear objetos, mejorar nuestra tecnología, construir refugios, etcétera. Todo ello mientras exploramos una gigantesca isla repleta de dinosaurios, lo que se perfila como uno de sus mayores atractivos.','/images/main-cards/ark-survival.jpeg',9.99,15,8.49,3,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (9,'Counter Strike','La cuarta versión de Counter-Strike llega a PC 12 años después que el juego original manteniendo la fórmula que lo convirtió en un fenómeno, pero también añadiendo nuevo contenido. Usa un nuevo motor gráfico que permite un salto visual, renovando mapas clásicos como de_dust, y añade nuevos mapas, facciones y modos de juego, volviendo a intentar enganchar a millones de jugadores en partidas por equipos entre terroristas y fuerzas del orden.','/images/main-cards/cs-anthology.jpg',3.99,15,3.39,1,2,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (10,'Doom Eternal - Deluxe','DOOM Eternal es la secuela del éxito de 2016, DOOM. Ahondando de nuevo en las raíces clásicas del género de acción en primera persona, la segunda parte desarrollada por id Software y Bethesda sigue apostando por la guerra sin cuartel contra los demonios en Xbox One, PS4, PC y Nintendo Switch.','/images/main-cards/doom-eternal.jpeg',3.99,15,3.39,2,3,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (11,'COD - Infinite Warfare','Call of Duty: Infinite Warfare es un juego de acción bélica futurista que presentará guerras a gran escala con su habitual narrativa militar. Se nos ofrecerá una nueva historia donde los jugadores deberán luchar contra el Settlement Defense Front para defender nuestro modo de vida a través del Sistema Solar. Esta nueva entrega de acción en primera persona, añadirá armas futuristas, pilotaje de naves espaciales y vehículos y una nueva serie de modos de juego, que volverán a ofrecernos características online y raciones de zombis.','/images/main-cards/cod-infinite.jpg',3.99,15,3.39,3,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (12,'Captain Tsubasa','Captain Tsubasa: Rise of the New Champions es un videojuego de fútbol arcade con toques de rol de acción desarrollado para PlayStation 4, Nintendo Switch y PC por Bandai Namco y Tamsoft. Adaptando la saga de anime y manga Captain Tsubasa, también conocida como Oliver y Benji, busca ofrecer partidos espectaculares con todo el carisma de la serie de animación, permitiéndonos disfrutar de personajes Tsubasa Ōzora, Kojirō Hyūga, Genzo Wakabayashi o Tarō Misaki.','/images/main-cards/captain-tsubasa.jpeg',5.99,15,5.09,1,2,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (13,'Dragon Ball Z Kakarot','Dragon Ball Game Project Z: Action RPG es un nuevo videojuego de rol y acción basado en Dragon Ball para Xbox One, PC y PS4 que nos narrará las aventuras de Goku durante la saga de Dragon Ball Z. Según ha confirmado CyberConnect2, responsables del videojuego, el título se centra en una de las etapas doradas del manga y el anime, contándonos los eventos sucedidos en aquellos momentos de una forma inédita y muy espectacular.','/images/main-cards/dbz-kakarot.jpeg',3.99,15,3.39,3,3,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (14,'FIFA 23','EA SPORTS™ FIFA 23 lleva El Juego de Todos al campo con los torneos de la Copa Mundial de la FIFA™ masculina y femenina, la incorporación de clubes femeninos y nuevas formas de jugar tus modos favoritos. Los avances en la tecnología HyperMotion2 proporcionan aún más acción y realismo al campo de juego en PS5.','/images/main-cards/fifa23.jpg',19.99,15,16.99,3,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (15,'Monster Hunter World','Monster Hunter World es el retorno de la serie a las consolas de sobremesa, permitiéndonos cazar criaturas gigantes en un entorno salvaje, ya sea en solitario o con tres cazadores con un nuevo sistema multijugador drop-in que permite cooperativo entre regiones. Mantendrá las señas de identidad, su sistema de creación y equipamiento para cazar monstruos, mientras mejoramos nuestras habilidades. Los recursos se podrán utilizar para mejoras y otro equipamiento. Su jugabilidad facilita explorar el mapa sin transiciones, con ciclo horario.','/images/main-cards/mhw.jpeg',6.99,15,5.94,1,2,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (16,'Crash Bandicoot Trilogy','Se trata de una remasterización de los tres primeros juegos de la serie Crash Bandicoot aparecidos en la consola PlayStation a finales de los 90 y desarrollados por Naughty Dog, pero mejorados con gráficos totalmente renovados, cambios estéticos y ciertas novedades jugables.','/images/main-cards/crashbandicoot.jpeg',6.99,15,5.94,1,3,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (17,'Days Gone','Days Gone es el videojuego de acción, zombies y supervivencia en mundo abierto exclusivo para PlayStation 4 desarrollado por Bend Studio. Nos invitará, encarnando al motero Deacon St. John, a sobrevivir en un escenario rural y desolado ambientado en la época actual plagado de voraces seres infectados por un misterioso virus.','/images/main-cards/daysgone.jpeg',6.99,30,4.89,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (18,'Devil May Cry 5','Devil May Cry 5 es la quinta entrega de la serie de juegos de acción en tercera persona o ‘hack and slash’ de Capcom para Xbox One, PS4 y PC, además de PS5 y Xbox Series X/S. Retomando la saga después del lanzamiento de la cuarta parte, hace diez años, Hideaki Itsuno director del título y de la mayoría de los capítulos de las aventuras de Dante, promete una vuelta a los orígenes y una jugabilidad frenética y desafiante con distintos personajes.','/images/main-cards/devilmaycry5.jpeg',6.99,20,5.59,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (19,'Devil May Cry HD','Comercializada en Xbox 360 y PlayStation 3 en 2012, Devil May Cry HD Collection es la versión diseñada para la actual generación de consolas y plataformas. Devil May Cry HD Collection llegará a Xbox One, PS4 y PC, e incluirá Devil May Cry, Devil May Cry 2 y Devil May Cry 3: Dante’s Awakening – Special Edition, así como gráficos en alta definición y 60 frames por segundo.','/images/main-cards/devilmaycryHD.jpeg',6.99,4,6.71,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (20,'Duke Nukem Forever','El antihéroe Duke Nukem regresa a Xbox 360 en su aventura más esperada, que ha estado la friolera de 14 años en desarrollo y a punto de ser cancelada varias veces. Duke Nukem Forever resucita a Duke con todo lo que eso conlleva: policías-cerdo volando por los aires, comentarios machistas y subidos de tono, y batallas contra jefes finales gigantes usando un largo repertorio de armas. Apuesta por una jugabilidad clásica, como la de los juegos de acción en primera persona de los años noventa, e incluye un modo multijugador online.','/images/main-cards/dukenuken.jpg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (21,'God of War','God of War: Ragnarok para PlayStation 5 es la secuela de God of War, el reinicio y a la vez secuela de los anteriores God of War para consolas PlayStation. Desarrollado por el prestigioso estudio Sony Santa Monica y con la dirección de Cory Barlog, encontraremos una nueva historia en la que Kratos deberá enfrentarse a diversos enemigos de inspiración nórdica. Explorando los mitos del Ragnarok, el apocalipsis que todo lo devorará según esta tradición del norte, la secuela se espera que llegue en 2021.','/images/main-cards/godofwar.jpeg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (22,'Mafia III','En la tercera entrega de la reputada saga Mafia, nos moveremos por New Bourdeaux, una ciudad inspirada en Nueva Orleans, en el año 1968, moviéndonos por los bajos fondos, entablando contactos con la mafia y entrando en la guerra de intereses y bandas de la época. El título de mundo abierto de 2K Games y Hangar 13, apostará por incluir nuevas mecánicas de negocios, un mayor plantel de vehículos y armas y una narrativa que hará homenaje a las clásicas películas del género negro.','/images/main-cards/mafiaIII.jpeg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (23,'GTA V','Grand Theft Auto V para PS5 es una versión mejorada y ampliada del GTA V original aparecido en PS3 en 2013. Contará con mejoras gráficas y el nuevo contenido incluido en su versión de PS4, como armas, vehículos o misiones, además de una banda sonora ampliada y GTA Online. Nos cuenta la épica historia de Michael, Franklin y Trevor en la ciudad de Los Santos y sus alrededores.','/images/main-cards/gtaV.jpeg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (24,'Hollow Knight','Hollow Knight, desarrollado por Team Cherry, ofrecerá una aventura de estilo bidimensional que combinará acción y plataformas en un mundo de fantasía medieval, el reino de Hallownest. Incluirá animaciones hechas con estilo tradicional, retos para el jugador, coleccionables por desbloquear y una banda sonora única.','/images/main-cards/hollowknight.jpeg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (25,'Visage','Visage es un videojuego de terror en primera persona desarrollado por SadSquare Studio, con énfasis en el horror psicológico, que nos llevará a vivir una serie de sucesos paranormales ambientados en los años ochenta, en un pueblo apartado y en un caserón enorme. Está pensado para consolas y PC.','/images/main-cards/visage.jpeg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (26,'Evil West','Una oscura amenaza consume la frontera americana. Como uno de los últimos agentes de una institución ultrasecreta dedicada a cazar vampiros, eres la última línea de defensa de la humanidad contra un terror profundamente arraigado que emerge ahora de entre las sombras. Álzate y conviértete en un superhéroe del salvaje Oeste, erradica la amenaza de los vampiros y ¡salva a los Estados Unidos!','/images/main-cards/evilwest.jpeg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (27,'Just Dance 2023','Just Dance 2023 Edition es el décimo cuarto videojuego de ritmo de baile de la serie Just Dance, precedido por Just Dance 2022, desarrollado y publicado por Ubisoft. Esta programado a lanzar el 22 de noviembre de 2022 para Nintendo Switch, PlayStation 5 y Xbox Series X y Series S, y en una fecha posterior para PC.','/images/main-cards/justdance2023.jpg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (28,'LOTR Gollum','The Lord of the Rings: Gollum, desarrollado y editado por Daedalic Entertainment para PC, PlayStation 4, Xbox One, Switch, PlayStation 5 y Xbox Series, es una aventura de acción centrada en la historia. Embárcate en un peligroso viaje como Gollum, en busca del único tesoro que conoce. Gollum es hábil y astuto, pero su personalidad está dividida. Una mente, dos egos: ¡tú decides!','/images/main-cards/lotrgollum.jpeg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (29,'Midnight Suns','Marvel\'s Midnight Suns es un nuevo RPG táctico ambientado en el lado más oscuro del Universo Marvel. Forma un equipo con los Midnight Suns y vive entre ellos mientras luchas contra las fuerzas demoníacas del inframundo para evitar que Lilith, la Madre de los Demonios, resucite a su maestro Chthon.','/images/main-cards/marvelmidnightsuns.jpeg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (30,'Naruto Storm Trilogy','Naruto: Ultimate Ninja Storm Trilogy es un recopilatorio exclusivo de la distribución digital que incluye los tres primeros juegos numerados de esta exitosa saga de juegos de lucha basados en el famoso manga creado por Masashi Kishimoto.','/images/main-cards/narutostorm.jpeg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (31,'One Piece Oddysey','One Piece Odyssey es un videojuego de rol y combates por turnos ambientado en el universo del exitoso manganime, si bien cuenta con una historia original y nuevos personajes que fueron creados bajo la atenta supervisión del mismísimo creador de la serie, Eiichiro Oda.','/images/main-cards/onepieceodyssey.jpeg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (32,'Park Beyond','¡En Park Beyond podrás crear el parque de tus sueños sin preocuparte por la fuerza de la gravedad! Una empresa en horas bajas te ha contratado para que, gracias a tu visionaria concepción de la arquitectura, construyas los parques temáticos más descabellados. Podrás crear esas atracciones con las que siempre habías soñado pero que no pueden existir en el mundo real. Forma equipo con Phil, un entusiasta veterano en esto de los parques; Izzy, una ejecutiva estricta pero afable, y un montón de alegres y apasionados personajes para construir una exitosa y rentable empresa de parques de atracciones.','/images/main-cards/parkbeyond.jpeg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (33,'Residen Evil 4','Resident Evil 4 es un remake del Resident Evil 4 original del 2005. Survival Horror de última generación reimaginado para el año 2023. Resident Evil 4 conserva la esencia del juego original, a la vez que introduce mecánicas de juego actualizadas, una historia reimaginada, e impresionantes gráficos de última generación que lo convierten en la experiencia de Survival Horror definitiva en la cual se cruzan la vida y la muerte, el terror y la catarsis.','/images/main-cards/re4.jpg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (34,'SpiderMan Miles Morales','¡Cava, lucha y construye! El mundo mismo está al alcance de tu mano mientras luchas por la supervivencia, la fortuna y la gloria. Adéntrate en extensiones cavernosas, busca enemigos cada vez más grandes para poner a prueba tu temple en combate o construye tu propia ciudad. ¡En el mundo de Terraria, la elección es tuya! Combinando elementos de los juegos de acción clásicos con la libertad de la creatividad estilo sandbox, Terraria es una experiencia de juego única en la que tanto el viaje como el destino son tan únicos como los propios jugadores.','/images/main-cards/spiderman.jpg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (35,'Steam Gift Card','¡Cava, lucha y construye! El mundo mismo está al alcance de tu mano mientras luchas por la supervivencia, la fortuna y la gloria. Adéntrate en extensiones cavernosas, busca enemigos cada vez más grandes para poner a prueba tu temple en combate o construye tu propia ciudad. ¡En el mundo de Terraria, la elección es tuya! Combinando elementos de los juegos de acción clásicos con la libertad de la creatividad estilo sandbox, Terraria es una experiencia de juego única en la que tanto el viaje como el destino son tan únicos como los propios jugadores.','/images/main-cards/steamcard.jpeg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (36,'The Devil In Me','¡Cava, lucha y construye! El mundo mismo está al alcance de tu mano mientras luchas por la supervivencia, la fortuna y la gloria. Adéntrate en extensiones cavernosas, busca enemigos cada vez más grandes para poner a prueba tu temple en combate o construye tu propia ciudad. ¡En el mundo de Terraria, la elección es tuya! Combinando elementos de los juegos de acción clásicos con la libertad de la creatividad estilo sandbox, Terraria es una experiencia de juego única en la que tanto el viaje como el destino son tan únicos como los propios jugadores.','/images/main-cards/thedevilinme.jpg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (37,'Thief','¡Cava, lucha y construye! El mundo mismo está al alcance de tu mano mientras luchas por la supervivencia, la fortuna y la gloria. Adéntrate en extensiones cavernosas, busca enemigos cada vez más grandes para poner a prueba tu temple en combate o construye tu propia ciudad. ¡En el mundo de Terraria, la elección es tuya! Combinando elementos de los juegos de acción clásicos con la libertad de la creatividad estilo sandbox, Terraria es una experiencia de juego única en la que tanto el viaje como el destino son tan únicos como los propios jugadores.','/images/main-cards/thief.jpeg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (38,'Xbox Card $10','¡Cava, lucha y construye! El mundo mismo está al alcance de tu mano mientras luchas por la supervivencia, la fortuna y la gloria. Adéntrate en extensiones cavernosas, busca enemigos cada vez más grandes para poner a prueba tu temple en combate o construye tu propia ciudad. ¡En el mundo de Terraria, la elección es tuya! Combinando elementos de los juegos de acción clásicos con la libertad de la creatividad estilo sandbox, Terraria es una experiencia de juego única en la que tanto el viaje como el destino son tan únicos como los propios jugadores.','/images/main-cards/xbox10.jpeg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (39,'Xbox Card $15','¡Cava, lucha y construye! El mundo mismo está al alcance de tu mano mientras luchas por la supervivencia, la fortuna y la gloria. Adéntrate en extensiones cavernosas, busca enemigos cada vez más grandes para poner a prueba tu temple en combate o construye tu propia ciudad. ¡En el mundo de Terraria, la elección es tuya! Combinando elementos de los juegos de acción clásicos con la libertad de la creatividad estilo sandbox, Terraria es una experiencia de juego única en la que tanto el viaje como el destino son tan únicos como los propios jugadores.','/images/main-cards/xbox15.jpeg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (40,'Xbox Card $50','¡Cava, lucha y construye! El mundo mismo está al alcance de tu mano mientras luchas por la supervivencia, la fortuna y la gloria. Adéntrate en extensiones cavernosas, busca enemigos cada vez más grandes para poner a prueba tu temple en combate o construye tu propia ciudad. ¡En el mundo de Terraria, la elección es tuya! Combinando elementos de los juegos de acción clásicos con la libertad de la creatividad estilo sandbox, Terraria es una experiencia de juego única en la que tanto el viaje como el destino son tan únicos como los propios jugadores.','/images/main-cards/xbox50.jpeg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (41,'Sonic Frontiers','¡Cava, lucha y construye! El mundo mismo está al alcance de tu mano mientras luchas por la supervivencia, la fortuna y la gloria. Adéntrate en extensiones cavernosas, busca enemigos cada vez más grandes para poner a prueba tu temple en combate o construye tu propia ciudad. ¡En el mundo de Terraria, la elección es tuya! Combinando elementos de los juegos de acción clásicos con la libertad de la creatividad estilo sandbox, Terraria es una experiencia de juego única en la que tanto el viaje como el destino son tan únicos como los propios jugadores.','/images/main-cards/sonic.jpeg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (42,'A Plague Tale','¡Cava, lucha y construye! El mundo mismo está al alcance de tu mano mientras luchas por la supervivencia, la fortuna y la gloria. Adéntrate en extensiones cavernosas, busca enemigos cada vez más grandes para poner a prueba tu temple en combate o construye tu propia ciudad. ¡En el mundo de Terraria, la elección es tuya! Combinando elementos de los juegos de acción clásicos con la libertad de la creatividad estilo sandbox, Terraria es una experiencia de juego única en la que tanto el viaje como el destino son tan únicos como los propios jugadores.','/images/main-cards/aplaguetale.jpg',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.products  (`id`,`name`,`description`,`image`,`value`,`discount`,`final_value`,`category_id`,`section_id`,`create_time`,`update_time`,`delete_time`) VALUES (43,'Juego de GamesHub','El mejor juego de la historia...realizado por gamesHub','/images/games/1669000750169.png',6.99,15,5.94,1,1,'2022-12-18 09:57:18',NULL,NULL);



/*INSERTA PRODUCTOS_CONSOLAS*/
INSERT INTO gameshub.products_consoles (`id`,`product_id`,`console_id`,`create_time`) VALUES (1,1,1,'2022-12-18 09:52:06');
INSERT INTO gameshub.products_consoles (`id`,`product_id`,`console_id`,`create_time`) VALUES (2,1,2,'2022-12-18 09:52:06');
INSERT INTO gameshub.products_consoles (`id`,`product_id`,`console_id`,`create_time`) VALUES (3,1,3,'2022-12-18 09:52:06');
INSERT INTO gameshub.products_consoles (`id`,`product_id`,`console_id`,`create_time`) VALUES (4,1,4,'2022-12-18 09:52:06');

/*INSERTA ROLES*/
INSERT INTO gameshub.roles (`id`,`name`,`create_time`,`update_time`) VALUES (1,'admin','2022-12-18 13:41:49',NULL);
INSERT INTO gameshub.roles (`id`,`name`,`create_time`,`update_time`) VALUES (2,'client','2022-12-18 13:41:49',NULL);

/*INSERTA USUARIOS*/

INSERT INTO gameshub.users (`id`,`names`,`surnames`,`email`,`password`,`address`,`role_id`,`phone`,`image`,`create_time`,`update_time`,`delete_time`) VALUES (1,'Manuel','Belgrano','manu@gmail.com','$2a$10$T5dhAs9qXNQ5g9r8pqymIucCc0q2laj0ggRIrpq315TixZ8o2c1DW','argentina123',1,'12345678','/images/users/1667867621671.jpeg','2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.users (`id`,`names`,`surnames`,`email`,`password`,`address`,`role_id`,`phone`,`image`,`create_time`,`update_time`,`delete_time`) VALUES (2,'Jose','San Martin','pepito@gmail.com','$2a$10$T5dhAs9qXNQ5g9r8pqymIucCc0q2laj0ggRIrpq315TixZ8o2c1DW','cordillera 456',1,'45678910','/images/users/1667867621671.jpeg','2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.users (`id`,`names`,`surnames`,`email`,`password`,`address`,`role_id`,`phone`,`image`,`create_time`,`update_time`,`delete_time`) VALUES (3,'Pedro','alvarez','jajaj@jajajaj','$2a$10$T5dhAs9qXNQ5g9r8pqymIucCc0q2laj0ggRIrpq315TixZ8o2c1DW','alla 123',1,'456465465','/images/users/1667867621671.jpeg','2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.users (`id`,`names`,`surnames`,`email`,`password`,`address`,`role_id`,`phone`,`image`,`create_time`,`update_time`,`delete_time`) VALUES (4,'peppa','pig','pepaPig@gmail.com','$2a$10$T5dhAs9qXNQ5g9r8pqymIucCc0q2laj0ggRIrpq315TixZ8o2c1DW','cordillera 789',1,'45678910','/images/users/1667867621671.jpeg','2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.users (`id`,`names`,`surnames`,`email`,`password`,`address`,`role_id`,`phone`,`image`,`create_time`,`update_time`,`delete_time`) VALUES (5,'pablo','perez','pperez@gmail.com','$2a$10$lndNorZs.5jMAMbIsS45YeyoiTy9Hil9ZIGJqGRcw/XFFAnXHop/m','calle falsa 123',1,'123456789','/images/users/1667867621671.jpeg','2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.users (`id`,`names`,`surnames`,`email`,`password`,`address`,`role_id`,`phone`,`image`,`create_time`,`update_time`,`delete_time`) VALUES (6,'jesus','alvarez','jp@gmail.com','$2a$10$2arIBpoH2okhQh9CVqQgI.HvXZdcIglviXdgme9R0VmIBMySUlhL6','colombia 123',1,'212121212121','/images/users/1667867621671.jpeg','2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.users (`id`,`names`,`surnames`,`email`,`password`,`address`,`role_id`,`phone`,`image`,`create_time`,`update_time`,`delete_time`) VALUES (7,'Salvador','Dali','salvador@dali.com','$2a$10$seLLEp3d7vxI0hla2xmAOeuXRI1ksckHXhJsHVmiojUFnsN0F0E8i','ahreloco123',1,'12345678','/images/users/1667867621671.jpeg','2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.users (`id`,`names`,`surnames`,`email`,`password`,`address`,`role_id`,`phone`,`image`,`create_time`,`update_time`,`delete_time`) VALUES (8,'Gonzalo','Potente','Gp@gmail.com','$2a$10$gxbH2UGUUiCIoPeaVvfn0elitgCZCPyGFV0IAoSBOuqWfV2jXOVDS','calle falsa 123',1,'123456789','/images/users/1667867621671.jpeg','2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.users (`id`,`names`,`surnames`,`email`,`password`,`address`,`role_id`,`phone`,`image`,`create_time`,`update_time`,`delete_time`) VALUES (9,'Felipe','Mendez','hotmail@hotmail.com','$2a$10$RaIejlgKiPuHoDQg.7i0G.49UxbohjS7kGavkg2dYgo7/sFa8AEm6','La Palmita',1,'123466771','/images/users/1670637997643.jpg','2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.users (`id`,`names`,`surnames`,`email`,`password`,`address`,`role_id`,`phone`,`image`,`create_time`,`update_time`,`delete_time`) VALUES (10,'Nahuel','Zelaya','nahuel@gmail.com','$2a$10$peH4mFUb1HA.DlvYM4/Xyetf.XKBBaXjtiXfBFnUnwTRLHGMr3cc2','hola mundo',1,'123456789','/images/users/1670726676581.png','2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.users (`id`,`names`,`surnames`,`email`,`password`,`address`,`role_id`,`phone`,`image`,`create_time`,`update_time`,`delete_time`) VALUES (11,'Gustavo','Avella','ga@hotmail.com','$2a$10$peH4mFUb1HA.DlvYM4/Xyetf.XKBBaXjtiXfBFnUnwTRLHGMr3cc2','Midgard',1,'123456789','/images/users/1670726676581.png','2022-12-18 09:57:18',NULL,NULL);
INSERT INTO gameshub.users (`id`,`names`,`surnames`,`email`,`password`,`address`,`role_id`,`phone`,`image`,`create_time`,`update_time`,`delete_time`) VALUES (12,'Nico','Susuki','nu@hotmail.com','$2a$10$peH4mFUb1HA.DlvYM4/Xyetf.XKBBaXjtiXfBFnUnwTRLHGMr3cc2','Japan',1,'123456789','/images/users/1670726676581.png','2022-12-18 09:57:18',NULL,NULL);

